#### Cluster configuration ####
default_box = "ubuntu/bionic64"
domain = "k3s.lab"
control_plane_name = "k3s-master"
worker_node_name = "k3s-worker-" 
control_plane_endpoint = control_plane_name + "." + domain + ":6443"
master_node_ip = "192.168.0.100"
worker_node_starting_ip = "192.168.0.20"
master_node_url = "https://" + master_node_ip + ":6443"
nbre_of_nodes = 1 #ne pas dépasser 10, append pour string !
k3s_version = "v1.25.11+k3s1"
#### END Cluster configuration ####

# vagrant config
Vagrant.configure("2") do |config|

  
  # master node
  config.vm.define 'master' do |master|
    master.vm.box = default_box
    master.vm.hostname = control_plane_name + "." + domain
    master.vm.network "private_network", ip: "#{master_node_ip}"
    master.vm.synced_folder ".", "/vagrant", type:"virtualbox"
    
    master.vm.provider "virtualbox" do |vb|
      vb.name = control_plane_name
      vb.memory = "2048"
      vb.cpus = "1"
      vb.customize ["modifyvm", :id, "--nic1", "nat"]
    end

    master.vm.provision "k3s master shell script", type: "shell", path: "scripts/k3s.sh", 
      env: {"MASTER_NODE_IP" => master_node_ip, 
            "NBRE_OF_NODES" => nbre_of_nodes, 
            "DOMAIN" => domain,  
            "WORKER_NODE_NAME" => worker_node_name,
            "NODE_START_IP" => worker_node_starting_ip,
            "CONTROL_PLANE_NAME" => control_plane_name,
            "K3S_VERSION" => k3s_version}

  end

  # Iteration on each nodes defined
  (1..nbre_of_nodes).each do |nodeIndex|
    #worker node definition
    config.vm.define "worker-#{nodeIndex}" do |node|
      node.vm.box = default_box
      node.vm.hostname = worker_node_name + "#{nodeIndex}" + "." + domain
      node.vm.network "private_network", ip: "#{worker_node_starting_ip}#{nodeIndex}"
      node.vm.synced_folder ".", "/vagrant", type:"virtualbox"
      
     
      node.vm.provider "virtualbox" do |vb|
        vb.name = worker_node_name + "#{nodeIndex}"
        vb.memory = "2048"
        vb.cpus = "1"
        vb.customize ["modifyvm", :id, "--nic1", "nat"]
      end
      
      node.vm.provision "k3s shell script", type: "shell", path: "scripts/k3s-nodes.sh", 
        env: {"MASTER_NODE_URL" => master_node_url,
              "DOMAIN" => domain, 
              "NODE_START_IP" => worker_node_starting_ip, 
              "WORKER_NODE_NAME" => worker_node_name,
              "MASTER_NODE_IP" => master_node_ip,
              "CONTROL_PLANE_NAME" => control_plane_name,
              "NBRE_OF_NODES" => nbre_of_nodes,
              "K3S_VERSION" => k3s_version}
  
    end #end worker node definition

  end #end nodes iteration
  

end
